export const FETCH_ARTISTS_START = 'FETCH_ARTISTS_START';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAIL = 'FETCH_ARTISTS_FAIL';
export const SHOW_ARTISTS_HANDLER = 'SHOW_ARTISTS_HANDLER';

export const FETCH_ARTIST_INFO_START = 'FETCH_ARTIST_INFO_START';
export const FETCH_ARTIST_INFO_SUCCESS = 'FETCH_ARTIST_INFO_SUCCESS';
export const FETCH_ARTIST_INFO_FAIL = 'FETCH_ARTISTS_FAIL';

export const FETCH_ALBUMS_START = 'FETCH_ALBUMS_START';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';
export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL';